language: node_js
sudo: false
node_js:
- 4
- 6
script:
- npm run copy-utils
- npm run ci
- chmod 777 ./test/shell_scripts/run_tests.sh
- "./test/shell_scripts/run_tests.sh"
deploy:
  provider: npm
  email: pearson-design-accelerator@pearson.com
  api_key:
    secure: VvElspSat5DNThm6KA2MfB1JBaT7SRjMyibwehQaFX+SIR5tpR8MHo9AE6n2pZhK63kmSA5wbTq1N8eAGIEmlTkgXwZZjddCZNSS8yDFY04iKSk1dBZF2ZRTnP+sedew+bzD9NC64xZml72aPq2+5ms5PVAfBb2gGsORwb2aNekibwZoRwlhkVlCH21aRy5mBJUJSL9GjRfZiUYZ3lPGrkJAlNarYTxemCJlcH2BzHy53ev653zcIwkDzehcVTEBpEZBgqUxZgbuxeAB++k6QnlT5R7z9P72EdllCR4uw3Dwhx28dii+qjdRx7BKzBcMbNkz95IvUttKDaSgAi6qrq6ssldNTpJR+bWeNI30BnsdKCi4vQbyOoxd50OkswD1dQUtV455RlStjG8QAGhr/Yb9G2U/ywr7l2HHhI7gjEhGaHvTM/6Oxw6PwmfMXOktSuHXyb/GkFiCUKbwFqXQQaUU1vz5BE2cmJSJe86Kms+qgWHOMZxqxf9JqCVPgoeXFpQBAC6e58YMwv4oX9hKLaIEVW8b9HwxK59lpAEy0kwq8NRU+0gLLcMCtpe58OOb73YCbsRYEH9Lcvn3e0MsoEovN3nIRsbJH/ip1bYqa8PXFdTCUgdAjyF9kUFGaoM1ZXsTmhzUgCOssV2swJOy1+HxzcW4AXsKS5FRCXnf8GA=
  skip_cleanup: true
  on:
    branch: master
    tags: true
env:
  global:
    secure: iVjSBp6kDmWrTwiy/+BSyWacbarWOwwNSZMNV1sxsT7uRT6Pdovx4Lbw1sOtGCzfaOUCUoMDuUUOv+AESr/KNd16SHziCFwHABQ2h7IZrCKPZiMlrqfH6zSCWUXNZ2/IHzoWkL+8yu27tdxV3BKus6but8z3cXijZtFfzLCcHZFZFDeaz77pfDyL07lGdmVndBWpzZ1Kz1dJSgktiAoqJuYQPgGFRo6ZquL8q5GakjzfnPEXEAJmmbrUX15+/drFgeznKNKSk0Fq30to2pOfoalNGfXDN2eXslE43GA7ZvD6efeh7yqZ6ZdyaVS0NLZvpoAAw+UL0/4KDKJ9zIx3Eejf0SL0T/itsJakVwfQe1ZaZTxbJo1ONH6w2idWIJXGl1/LwA51HgfPSSCpfwYLAW8tL/1mkXdu+FQ+d5ZDRK1wV2g/LUCzK6lDOQLhTDThdewYuURlrXqHDLfUNApfzQqMZwvuHutXU4zhxbgnSF3A5Arpyx2oUvWxHahNfVup6hnRi1y5q3vgEKNDRxTxnaQhUcUkzRM3gTsmSqeM7DU6aKmvBv8bVkjvwntEe2j6R9gr+9pxyZBwbTmVcyZ0BxyBF52+drS1y/vB74Ep0cclrTjalw8961W8VInCkbloI5pu6tPJkFWTxksOV7IyrWUnm4YCyyJumqc7g1lkrRA=
