language: node_js
sudo: false
node_js:
- 4
- 6
script:
- npm run ci
- chmod 777 ./test/shell_scripts/run_tests.sh
- ./test/shell_scripts/run_tests.sh

deploy:
  provider: npm
  email: pearson-design-accelerator@pearson.com
  api_key:
    secure: I7MhEd++LqQyxQcivH7thVwazRHmV1By4TzjdKicHHur4qHaQzjiq5a5pM7LtPzrDbgxZapBwA/9okz13iSGeqG+/Nks8Nc2ac1wGOpnewnOSNnCw4e8tJT7Ug88s5cdcIfKeA0GhzUrRie5xEADBk1+9T+UXUujGiUNYcVftmqwV2xEHeE2FqjLGat0OLLx33llpM7ppt3pC00W7dRz/1IEY1Ov/U4lSqEqlppGfbLhi3X7SrgK66eqAiBS21lHUc2EF+/9Z5cebYjVMB6Wlbb6DcbYsm2rUEXiNmKu23P89yOBgLx9VEImDnyfOAfwGXX0H8fHgDXXC0dQboC9pCcBMbe6v4PH9zg0qs2pfUbsBTEX8m376dI1jm8RZhwVAQ0o1wsqLe0d11+p9hEROp0vs4Vgi7Uern7Fzyvpsi/b/ZpxIxbldqbhyb9GVgcrepfBvG3OFCVxNTcjYjyUjn1BATHZA9MdFQgsZTf//AjsbuQp6KGEPzCUTRLlzc5TvJ6LwsPw5Kvbj5hTLUblcgbPNTQH31vcHxkqWaQ8cnwSFinjiKJtdYn5SCHHpMLxdGSg2Pr16mNP+uByf6/A7tpb304TOJGzv3WQdZrwaOTG0KFRIGb4Lurjn+sZXzIsKkboUsJDijdnuxOLCl5a7aPT0JfP+I2IR0GHcAdpG0M=
  skip_cleanup: true
  on:
    branch: master
    tags: true
env:
  global:
    secure: iVjSBp6kDmWrTwiy/+BSyWacbarWOwwNSZMNV1sxsT7uRT6Pdovx4Lbw1sOtGCzfaOUCUoMDuUUOv+AESr/KNd16SHziCFwHABQ2h7IZrCKPZiMlrqfH6zSCWUXNZ2/IHzoWkL+8yu27tdxV3BKus6but8z3cXijZtFfzLCcHZFZFDeaz77pfDyL07lGdmVndBWpzZ1Kz1dJSgktiAoqJuYQPgGFRo6ZquL8q5GakjzfnPEXEAJmmbrUX15+/drFgeznKNKSk0Fq30to2pOfoalNGfXDN2eXslE43GA7ZvD6efeh7yqZ6ZdyaVS0NLZvpoAAw+UL0/4KDKJ9zIx3Eejf0SL0T/itsJakVwfQe1ZaZTxbJo1ONH6w2idWIJXGl1/LwA51HgfPSSCpfwYLAW8tL/1mkXdu+FQ+d5ZDRK1wV2g/LUCzK6lDOQLhTDThdewYuURlrXqHDLfUNApfzQqMZwvuHutXU4zhxbgnSF3A5Arpyx2oUvWxHahNfVup6hnRi1y5q3vgEKNDRxTxnaQhUcUkzRM3gTsmSqeM7DU6aKmvBv8bVkjvwntEe2j6R9gr+9pxyZBwbTmVcyZ0BxyBF52+drS1y/vB74Ep0cclrTjalw8961W8VInCkbloI5pu6tPJkFWTxksOV7IyrWUnm4YCyyJumqc7g1lkrRA=
